### ISSUE TITLE
How to redirect back to route post login?

### ISSUE THREAD

**Issue by landland** [zimme/meteor-iron-router-auth#12]
Hi there, I'm trying out your package and am not having much success. What I'd like to do is redirect all of my routes to a login page if the user isn't logged in, and then after the login is successful redirect them back to the route they came from. Is this possible? If so, I would love an example. I've been through the docs and examples but haven't been able to piece it together. Thanks for any insights!

**Comment by zimme** [comment]
If you use the plugin option you should be automagically redirected back to the requested page once logged in. if you're using the hooks manually you can use the noAuth hook on the login route to make this possible, this hook can be used on all routes where you don't want authenticated users to see. i.e. the login route as it's not necessary to use the login route when you're already logged in.

**Comment by landland** [comment]
hi @zimme thanks for your reply. It seems I tried just about every combination except that one I was supposed to to make it work :) thanks for the help, it works beautifully!

**Comment by zimme** [comment]
I'm working with my packages tonight hopefully I'll have some better examples and documentations after.
