### ISSUE TITLE
Can't Get Authorize to work

### ISSUE THREAD

**Issue by teckno101** [zimme/meteor-iron-router-auth#21]
First of all, thank you for all the work on this package. This makes securing my app a breeze.

I'm having an issue with authorization. Here's my configuration for the overall plugin:
```javascript
Router.plugin('auth', {
	authenticate: {
		route: 'login'
	}
});
```

and I'm trying to block all access to a page with this:
```javascript
Router.route('/teacherClassScreen', {
	authorize: {
		deny: function(){
			return true; //doesn't matter if this is set to true or false
		}
	}, name: 'teacherClassScreen'
});
```

I'm really trying to add role authorization in, but I can't seem to get authorize work in specific routes. It just skips over all the code in the route itself and defaults back to the plugin configuration in my first code snippet.

I know I'm doing something wrong and this isn't really a bug, so thanks in advance for your help.

**Comment by zimme** [comment]
Make sure you're not using the `insecure` package, it will override the allow/deny rules.

Also, route level configuration is merged with plugin level configs, so just setting `authorize` config on route should just add `authorize` configs to the `authenticate` configs of the plugin.

I'll try and work on the documentation for this package pretty soon just to try and make thinks clearer.

**Comment by teckno101** [comment]
Thanks so much! I think it was the insecure package that was screwing everything up. Clearing that up in the documentation would definitely be helpful.

Thanks not only for your help but an awesome package!

I'm just going to include the code I ended up using here in case anyone else stumbles upon this.

```javascript
//Custom options
Router.plugin('auth', {
	authenticate: {
		route: 'home'
	},
	authorize: {
		allow: function(){
			return false; //by default block access
		},
		template: 'notAuthorized'
	},
	except: ['home']
});
```
```javascript
Router.route('/studentPage', {
	authorize: {
		deny: function(){
			if (Roles.userIsInRole(Meteor.user(), ['student'])){
				return false; //allow
			} else {
				return true; //deny
			}
		},
		template: 'notAuthorized'
	},
	name: 'studentPage'
});
```

**Comment by zimme** [comment]
Yes, I'll clarify that in the docs. The package should be console warn about the insecure package being installed and telling to you remove it to respect the allow/deny rules.
