### ISSUE TITLE
Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?

### ISSUE THREAD

**Issue by LeCoupa** [zimme/meteor-iron-router-auth#24]
Hello,

Just got the following error with the default configuration:

    Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?

Here is the code, what should I do?

    Router.plugin('auth', {
      authenticate: {
        route: 'Login',
        except: ['Login']
      }
    });

**Comment by zimme** [comment]
First, to get the default configuration you need to just do this:
```js
Router.plugin('auth');
```
Anyways, lets see.
I assume you're using the latest version of `iron:router` and `zimme:iron-router-auth`.

Do you have any other `onBeforeAction` function on the `Login` route which isn't calling `this.next()`? Could you please paste the code for the `Login` route?

**Comment by zimme** [comment]
So check the name of the route and see that it is in fact `Login` with a uppercase "L" because I got the same error when it couldn't find the route with the name specified in `route`

**Comment by zimme** [comment]
So I just found the issue, it's a problem with the except option not getting overridden properly in the plugin. I'll have a look at it later today. Need to finish what I'm working on right now.

Thank you for the report.

**Comment by zimme** [comment]
The problem is here:
```js
Router.plugin('auth', {
  authenticate: {
    route: 'Login',
    except: ['Login']
  }
});
```
Should be this:
```js
Router.plugin('auth', {
  authenticate: {
    route: 'Login'
  },
  except: ['Login']
});
```

**Comment by zimme** [comment]
I'll add options checks to my todo list.
