### ISSUE TITLE
Merge packages

### ISSUE THREAD

**Issue by zimme** [zimme/meteor-iron-router-auth#4]
Hey @fuatsengul

If I understand correctly you forked @xpressivecode's package to keep an up-to-date package available on atmosphere. Is this correct?

I however made this package which is a re-write and uses iron:router's plugin/hook system and I also added a cleaner way of handling authorization.

Are you intending to update you package with more features/bug fixes?
I'm thinking we might wanna consolidate our work?

What do you think?

**Comment by fuatsengul** [comment]
Hi @zimme
I exactly did as you told indeed.
Of course we might (and should) consolidate these packages, It would be great that there's one solid package that does its job correctly :)

**Comment by zimme** [comment]
Awesome.

Here's my thoughts on how we should continue.

I feel we should continue the work from my codebase as it adds hooks and plugins "the right way" and isn't as invasive as the original project. I believe using iron:router's plugin system is the way to go and not to use a "knife" and cut into and change the business-logic of iron-router.

Depending on how you wanna be part of this package I'll either give you access to this repo and add you as a collaborator on atmosphere or if you don't want that I'll just continue "alone" and you can submit PR's just like everyone else if you feel bugs need fixing or features are lacking.

I'll try and write up a PR for your package that shows that it's deprecated in favor of this package.
You should then un-migrate the package on atmosphere too, to make sure "new" users chooses this package instead. This shouldn't affect users of your package except that they will not get new updates for bugs/features.

New features should be developed in it's own branch and we would be using PR's as a way of discussing them before merging.

How do you feel we should continue? Does this sound like a viable plan? Should we publish a new package under a new namespace? (I don't think we should as it would just confuse people unnecessarily).

**Comment by zimme** [comment]
@XpressiveCode

If you want in on this just say the word and I will gladly work with you too.

**Comment by fuatsengul** [comment]
Hi @zimme,
I'm not a expert JS coder but I would gladly be a part of this. It can be on your call and I can follow it about namespacing and collobrator state. 

Actually, I need a detailed role-based authorisation mechanism in my project and I wasn't be satisfied with meteor-roles and iron-router-auth. 

I need to authorize users to access some pages with their roles and need to authorize some functions on these pages separately, and manage this mechanism easily.

So, I wrote a configuration file like below, and I want to hear your ideas on it.
Maybe we can develop a new authorisation engine together.
```
{
	"roleConfigurations" : [
		{
			"roleName": "default-user",
			"allowedPages" : ["Map", "editProfile"],
			"allowedFunctions" : []
		},
		{	"roleName" : "user-admin",
			"allowedPages" : ["userAdmin"],
            "baseRoles" : ["default-user"],
			"allowedFunctions" : ["viewAllUsers","addUser", "editUser", "removeUser"]
		},
		{	"roleName" : "device-admin",
			"allowedPages" : ["deviceAdmin"],
            "baseRoles" : ["default-user"],
			"allowedFunctions": ["resetDevice", "editDeviceInfo"]
		},
		{	"roleName" : "test-user",
			"allowedPages" : ["testPage0"],
           	"baseRoles" : ["default-user"],
			"allowedFunctions": ["testFunc0", "testFunc1", "testFunc2"]
		},
		{	"roleName" : "system-admin",
			"allowedPages" : ["userAdmin", "deviceAdmin", "testPage0"],
            "baseRoles" : ["test-user", "device-admin", "user-admin","default-user"],
			"allowedFunctions": ["admFunc0", "admFunc1", "admFunc2" ]
		}
	],
	"templates" : [
		{
			"name" : "Map",
			"title" : "navbar_homeBtn",
			"path" : "/",
			"subscriptions" : ["Pointers"]
		},
		{
			"name" : "userAdmin",
			"title" : "navbar_userAdminBtn",
			"path" : "/userAdmin",
			"subscriptions" : ["users"]
		},
		{
			"name" : "testPage0",
			"title" : "navbar_testPage0Btn",
			"path" : "/testPage0",
			"subscriptions" : []
		}
	]
}
```

**Comment by zimme** [comment]
I've given you pull/push access to this repo and added you as a collaborator on atmosphere.

Work against `devel` branch or a separate branch for a new feature or more advanced bugs.
This way we can create pull requests and discuss/review before merging into `devel`.

On the authorization stuff you brought up here I feel the roles package is actually in the direction I want but maybe needs some work. I'm going to start a discussion with Eric to see if maybe we can't do a more advanced rewrite that have permissions and roles packages and if used together gives the users some extra features.

I've actually been thinking that I should take some time and look over the authorize logic in this package to see if there's maybe a simple way to make the authorize logic show different templates/routes depending on return values of the allow/deny rules.

**Comment by zimme** [comment]
This package is doing what I believe it should do and I don't feel we should extend its domain further.

But maybe a package that makes applying permission/roles checks to functionality could be done?

**Comment by zimme** [comment]
@queso: How do you feel about working together?

We seem to have a bit of overlap in functionality but I also have support for authorization for routes.

My first thought is to make a accounts-entry re-write which is a bit lighter which builds upon this package?

Give users a choice, either use accounts-entry and you'll get routes setup with templates or use this package and set up routes and templates manually.

Any thoughts?

**Comment by queso** [comment]
What are you guys looking for here?

I haven't really been public about it, but accounts-entry is being deprecated in favor of useraccounts moving forward.

**Comment by zimme** [comment]
@queso: Ok, Here's a bit of background.

I was using accounts-entry package to begin with but I felt I didn't need all the ready made templates and routes but I wanted the ability to easily specify redirect/render logic in case users wasn't logged in but use my own routes and templates.

I found iron-router-auth that XpressiveCode had made and it wasn't very active and decided to make a rewrite which used the hooks and plugin system of iron-router to do this and here's the result of that.

Me and @fuatsengul just recently merged our efforts as he was maintaining a fork of the original package, and having 2 packages which works almost the same seemed redundant.

Then I thought maybe this package could be used for the redirect/render logic for accounts-entry, i.e. accounts-entry uses this package to configure sign-in/sign-out routes and stuff like that. One benefit would probably the support for authorization for routes my packages would add.

In light of the useraccounts packages I will need to re-evaluate the need for this package and maybe have a talk with @splendido instead.

**Comment by splendido** [comment]
Hi there!
...happy to talk with you whenever you wish ;-)

Just to let you know, useraccounts already has its own logic for redirects and also an `ensureSignedIn` method to protect pages from non-logged in users (I must admit its already to be converted to a iron:router 'plugin' though...).
I'm also trying to draft a 2.0 version for useraccounts made up by a number of both base and plugin-packages: and one of these should be devoted to the redirect/protection logic.

While I feel general roles checking to prevent some user to access some page might be a bit out of the useraccounts's scope, I'd say any mechanism to configure custom rules to be used to prompt a login page on certain routes for non-logged in users are surely of interest.

This said, I'm always happy to get collaborations going.

Have a nice evening, Luca

**Comment by zimme** [comment]
@splendido
Sounds great, I'm thinking we should try and consolidate our efforts into useraccounts 2.0. I've hooked into iron-routers plugin system quite well. We could go over this package and use it as a base/inspiration for 2.0's redirect/render and route configuration logic.

I have support for both redirect to a user configured login route or render a user configured template in-place when users isn't logged in. Once you hit the route after login another hook runs to check allow/deny rules configured on the route to see if you're authorized to access the route. I also have a hook that I run on routes where you don't want a logged in user to use.

i.e. When a user is logged in and hit the `login` route he gets redirected to the `dashboard` route.

I think useraccounts 2.0 should make it possible to use only the core if you wanna configure your own routes and make your own templates.

On a side note I have an active issue on iron:router related to make it easier to look up nested options in iron:router which makes it easier to configure iron:router plugins and keeping the settings in their own namespaces in Router.configure/Route setups. ([#1080](/EventedMind/iron-router/pull/1084))

**Comment by zimme** [comment]
One key aspect of this package was ease of use. If you use the routes `login`, `logout`, `dashboard`, `enroll`, `resetPassword`, `forgotPassword` and `home` the only thing you need to add to your app for this plugin to work is `Router.plugin('auth');`

**Comment by splendido** [comment]
...and one key aspect for useraccounts is *customization*, so everything frome the routes' name to redirects' destination (to cite a few) can be changed based on developer's wish. ;-)

Lets have a look at the [docs](https://github.com/meteor-useraccounts/core) especially at the [routing](https://github.com/meteor-useraccounts/core/blob/master/README.md#routing) section.

So far I tried to keep things as general as possible as well as fully customizable, so I guess there might be something to be exposed to the configuration API  but a package like `useraccounts:auth-plugins` (or similar) should have its reasons to exists :-)

The only thing is, as I see it, it won't be a stand-alone package to be possibly used without useraccounts base packages...
Take or leave ;-)

**Comment by zimme** [comment]
Yes, customization was key to my package too. That's why you can configure
all aspects of it :)

Where I see this package being integrated into yours, starting from 2.0, is
in the useraccounts:core package and a separate useraccounts:authorization
package which will add the ability to set allow/deny rules on the routes or
globally (to check if user should have access to the route).

The way I see all this is. We take your package and keep the best parts and
integrate the best parts from my package into yours, and what we get is a
newer, better, SINGLE package for doing login logic kind of stuff, which is
as easy to use as possible but also as customizable as possible :)

Doing this with version 2.0 of your package, which you said you was looking
into re-factor a bit, would give us the ability to work together to try and
come up with the best possible way to do this. Try and figure out the
cleanest api, configuration, integration with iron:router and so on.

How do you feel about this? Is it at all interesting?

**Comment by splendido** [comment]
:+1:

**Comment by zimme** [comment]
@splendido, I'll close this issue... but lets keep in touch on the packages merge

**Comment by splendido** [comment]
sure!
I've just added you to the [trello roadmap for useraccaounts@2.0](https://trello.com/b/NWHVV4ZA/useraccounts-2-0-roadmap): feel free to add/comment stuff!

**Comment by zimme** [comment]
:+1:
