### ISSUE TITLE
If a route uses waitOn, iron-router-auth will not redirect to login

### ISSUE THREAD

**Issue by MathiasJakobsen** [zimme/meteor-iron-router-auth#5]
The iron-router-auth has the following plugin settings:

```
Router.plugin 'auth',
  except: ['login','logout','register','forgotpassword','resetpassword']
```

I have a route called dashboard, with the following settings:

```
Router.route '/dashboard',
  name: 'dashboard'
  template: 'dashboard'
  waitOn: ->
    Meteor.subscribe 'rooms'
  data: ->
    rooms.find()
```

Even though dashboard IS NOT included in the except array, "/dashboard" does not get redirected, as it should.

**Comment by zimme** [comment]
I'll have a look later tonight and hopefully I will have a solution for you by tomorrow otherwise this will have to wait for about 2 weeks as I'm going to Thailand and I've decided not to bring my laptop =P

**Comment by MathiasJakobsen** [comment]
Sounds great! Besides this little issue, it is an awsome package :)

**Comment by zimme** [comment]
Ok, I can't reproduce this problem.

Could you please provide a small reproduction git repo which I can clone and see this problem.

I'll have some time to kill on the flight and I can take a look as long as I can get access to a reproduction of the problem before boarding, as I won't be having internet in the air :smile:

**Comment by zimme** [comment]
@MathiasJakobsen 

Is this still a problem for you?

**Comment by MathiasJakobsen** [comment]
Hi Simon,

Yep, I still have the problem. I will create the repo ASAP - thanks for taking a look!

**Comment by MathiasJakobsen** [comment]
I created a new project with the same routes and template, as in my project. Like you, I can't reproduce the problem. I can figure out why it is happening in my real project, since I use the exact same setup. I'll guess I will have to figure it out. Thanks for offering your help, anyways!

**Comment by zimme** [comment]
No problem, maybe there's some other hook or waitOn/subscription or something that is keeping my hooks from running properly...

I hope you get to the bottom of the problem.

Feel free to use this thread to ask for help once you get a bit closer =)

**Comment by romant** [comment]
@mathiasjakobsen did you ever figure out what caused this?

as effectively having:

```
waitOn: function ()
    {
      return Meteor.subscribe('locations');
    }
```

Ends up in a 'loading' template with the plugin. The minute I replace it with the following - it works:
```
    waitOn: function ()
    {
      if (Meteor.user())
        return Meteor.subscribe('locations');
    }
```

any way to do this globally instead of inserting a user check on every route?

Thank you.

**Comment by zimme** [comment]
If the locations subscription should only be used by logged in users then i'd just do the check if user is logged on serverside in the publication.

**Comment by zimme** [comment]
```js
Meteor.publish({
  locations: function() {
    if (this.userId)
      return Locations.find({userId: this.userId});
    else
      this.ready();
  }
});
```
Something like this

Then you should be able to subscribe without checking if the user is logged in.

**Comment by romant** [comment]
Brilliant. Thank you @zimme. That worked perfectly.
