### ISSUE TITLE
How can I redirect already logged in users, say, in the case that I need to collect payment info if not already provided?

### ISSUE THREAD

**Issue by faceyspacey** [zimme/meteor-iron-router-auth#7]
Or does this only work for redirecting logged in and non-logged in users?

Also what's the difference between Authenticate and Authorize?

**Comment by zimme** [comment]
For the case you need to redirect the user to a payment collection page if
no payment information is available before access to a route is given. I
would setup an allow or deny rule to check for payment info and return
false (allow rule) or true (deny rule) if there isnt any.

Autenticate - check who someone is, by login

Authorize - check access rights by allow/deny rules

**Comment by faceyspacey** [comment]
where should i put: 
````
this.redirect('/payment_info');
````
?

What code executes after I return false from an allow rule so that I can then redirect the user to the payment info page?

**Comment by zimme** [comment]
```js
Router.route('/cash-out', {
  name: 'cashOut',
  authorize:
    route: 'paymentInfo',
    allow: function() {
      ...check if payment info is available for user, return true or false...
    }
});
```

This code should redirect a user to the route `paymentInfo` when the allow rule returns `false`

**Comment by zimme** [comment]
You could put the rules globally also, i.e. will run on all routes which isn't defined in `except` option.

```js
Router.plugin('auth', {
... options here...
});

**Comment by faceyspacey** [comment]
oh i gotchu now. ..but if I did want to run a handler rather than redirect to a route, how would i modify your code so instead of where you have 

````
route: 'paymentInfo',
````

I could have something like:
````
handler: function() {}
````

That would allow me to do more with steps and other values set in Session vars, like in a wizard.

**Comment by faceyspacey** [comment]
I guess what I'm asking more succinctly is how can I dynamically select the route I redirect the user to? For example, you have a signup wizard, and user's leave at various steps before signing up. But then they return. In this case, i'd look up on the user object the step they achieved, and then dynamically choose a route to send the user to.

**Comment by zimme** [comment]
You could use the template option instead to show the payment_info template
instead of the regular template and do something there. I'm afraid how to
handel the payment stuff is out of the scope of this package.

Maybe you might even be better off using a onBeforeAction hook separatly
from this package to achive what you want/need.

**Comment by zimme** [comment]
I was thinking about maybe maning route and template accepting functions to enable dynamic routes/templates.

**Comment by faceyspacey** [comment]
I'll fork it and make a pull request. Can you give me a quick tip of what I'd change. I assume just find the code where the authorize 'route' property is defined and alter it in a few places to accept a function instead. What are those places?

**Comment by zimme** [comment]
I'm not sure if making route/template accept functions or making it
possible to return a string from allow/deny is the way to go.

**Comment by faceyspacey** [comment]
what other options are there?

**Comment by zimme** [comment]
The two options I'm considering is

1. Make route/template accept a function that returns the Template/View/Route or the `string` name of the template/route to use

2. Make it possible to return a `string` of the name of the template or route to use

**Comment by zimme** [comment]
Another thing that's related to this is

Do we need to add dynamic routes/templates to the authenticate hook too? First thought is it's not necessary.

**Comment by zimme** [comment]
```
authenticate: {
  template: function() {
    return 'templateName';
  }
},
authorize: {
  route: function() {
    return 'routeName';
  }
}
```
These are available now in `3.1.0-rc.3`, hopefully they can help you out.

**Comment by zimme** [comment]
@faceyspacey, can I close this issue?

**Comment by faceyspacey** [comment]
Yea that's cool

On Saturday, June 6, 2015, Simon Fridlund <notifications@github.com> wrote:

> @faceyspacey <https://github.com/faceyspacey>, can I close this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zimme/meteor-iron-router-auth/issues/7#issuecomment-109652155>
> .
>


-- 
James
from
http://faceyspacey.com - "The Startup Incubator"
http://facebook.com/faceyspacey
http://twitter.com/FaceySpacey
http://www.linkedin.com/in/faceyspacey
