### ISSUE TITLE
login.coffee on client at Examples

### ISSUE THREAD

**Issue by dr-dimitru** [zimme/meteor-iron-router-auth#8]
Hi,
I used yours login example but run into issue and broke my head on it. But finally solved, so:
 - My issue was:
```shell
"xyz" field needs either "schema" or "collection" attribute
```

 - At [this file](https://github.com/zimme/meteor-iron-router-auth/blob/master/examples/autoform/login/client/login.coffee#L51) on the last line you reference the `loginSchema` variable
 - To solve my issue I've changed last line to:
```coffeescript
Template.login.helpers
  settings:
    class: 'form-login'
    id: 'loginForm'
    schema: 'loginSchema'
```

Any comments around it?

**Comment by zimme** [comment]
When I run the login example app I can't replicate this problem so the only thing I can think of is.

If you used the example outside of a package i.e. in the app code then the variable `loginSchema` might not be file scoped and is attached to the `window` scope and the schema/collection attribute I believe look for `string` on the `window` object.

**Comment by dr-dimitru** [comment]
I have a `Schema ` attached to window, inside I've created `Schema.AccountsLogin` to store `SimpleSchema` with login options, please see code below.

Here is real code:
__`lib/structure.coffee: `__
```coffeescript
@Schema = {}
```
__`collections/login.coffee: `__
```coffeescript
Schema.AccountsLogin = new SimpleSchema
  username:
    type: String
    regEx: /^\+?\(?\d+\)?(\s|\-|\.)?\d{1,3}(\s|\-|\.)?\d{4}/
    label: i18n.get i18n.currentLocale, 'accounts.username.label'
    autoform:
      type: "tel"
      placeholder: i18n.get i18n.currentLocale, 'accounts.username.placeholder'
  password:
    type: String
    min: 6
    label: i18n.get i18n.currentLocale, 'accounts.password.label'
    autoform:
      type: "password"
      placeholder: i18n.get i18n.currentLocale, 'accounts.password.placeholder'


Schema.AccountsLogin.messages
  'auth login': 'Incorrect email, username or password'
  'auth password': ' '
```
__`client/../../../index.coffee :`__
```coffeescript
AutoForm.hooks
  accountsLogin:
    onError: (operation, error, template) ->
      if error instanceof Meteor.Error
        if error.reason in ['Incorrect password', 'User not found']
          context = AutoForm.getValidationContext @formId

          context.addInvalidKeys [
            name: 'login'
            type: 'auth'
          ,
            name: 'password'
            type: 'auth'
          ]

        else
          console.warn error.message

    onSubmit: (insertDoc, updateDoc, currentDoc) ->
      {login, password} = insertDoc

      cb = (error) =>
        @done error

      Meteor.loginWithPassword login, password, cb

      false


Template.login.helpers
  settings:
    class: 'form-signin'
    id: 'accountsLogin'
    schema: 'Schema.AccountsLogin'
```

**Comment by zimme** [comment]
Ok

In this case I believe `schema: 'Schema.AccountsLogin'` will always work as `Schema.AccountsLogin` will be looked up during run-time. `schema: Schema.AccountsLogin` however will only work if `Schema.AccountsLogin` is defined before the helper tries to use it.

**Comment by zimme** [comment]
I don't think this is a bug but just the "normal" issues with file load order that comes with meteor

**Comment by dr-dimitru** [comment]
@zimme yes, if it is will be mentioned at docs, what you can pass a string instead of object

**Comment by zimme** [comment]
If you feel it will keep others from running into the same issues you had while trying to use my login example in their apps, then I will gladly add a README.md to the example where this is brought up as a note.

Any suggestions on how to make this note as clear as possible to users?

**Comment by dr-dimitru** [comment]
@zimme but no, I know exact order of those files is loading:
1. `lib/*`
2. `collections/*`
3. All other

But anyways - yes add please something like:
 > If schema or collection attribute is not available in your template or template helper, you can pass it as a string instead of object reverence, for more read [this thread](https://github.com/zimme/meteor-iron-router-auth/issues/8#issuecomment-72905250)
```coffeescript
# Instead of reference:
Template.name.helpers
   schema: mySchemas.someSchema
   collection: mycollection
# Use string:
Template.name.helpers
   schema: "mySchemas.someSchema"
   collection: "mycollection"
```

You free to improve or change suggested text.

**Comment by zimme** [comment]
Yes.

In your provided code the `client/../../../index.coffee` file will load before `collections/login.coffee` because none of them is in the `lib` folder and after that it's loaded alfabetically. This results in autoform trying to use a reference that isn't defined yet when not using a  `string`. Had it been `lib/collections/login.coffee` then the `Schemas.AccountsLogin` varaible would have been defined.

That is what I get from all the information provided. However the important part is that you solved it =)

Thank you for the note, it seems like a very good way to bring this head-scratcher to light. =)
