### ISSUE TITLE
Update to iron:router 1

### ISSUE THREAD

**Issue by zimt28** [zimme/meteor-iron-router-auth#9]
I was just able to update to iron:router 1 as https://github.com/yoolab/iron-router-i18n/ finally supports it, but my auth setup stopped working /: I just renamed `auth` to `authenticate` and thought it might work, but it doesn't. Here's my code.

```coffeescript

# Router Configuration #

Router.configure
  layoutTemplate: 'MasterLayout'
  loadingTemplate: 'Loading'
  notFoundTemplate: 'NotFound'
  templateNameConverter: 'upperCamelCase'
  routeControllerNameConverter: 'upperCamelCase'
  authenticate: 'login'
  i18n:
    defaultLanguage: 'de'
    languages: ['de', 'en']
    setLanguage: (lang) ->
      TAPi18n.setLanguage(lang)  if Meteor.isClient

Router.onBeforeAction 'authenticate', except: [
  'login'
  'cases.print'
  'barcode'
]

Router.onBeforeAction 'loading', except: [
  'cases.print'
]
```

I've tried some things I found in the readme, but I find it hard to understand. Any idea how I can get it running again?

**Comment by zimme** [comment]
It's probably related to this issue yoolab/iron-router-i18n#33

**Comment by zimt28** [comment]
I just noticed it works when I'm logged in and then log out, I will be redirected to my login screen (both with and without iron-router-i18n). When I remove iron-router-i18n and go to my `localhost:3000/`, I will still not get redirected.

**Comment by zimt28** [comment]
Quick update: The fixes for [these](https://github.com/yoolab/iron-router-i18n/issues/33) [two](https://github.com/yoolab/iron-router-i18n/issues/32) issues didn't change anything. It might be an `iron:router` [https://github.com/iron-meteor/iron-router/issues/1247]() issue, where `onBeforeAction` now runs at a different point. Using `onRun` fixed this problem for me, which for me appears to be calling the authentication stuff "too late", but it does the job.

**Comment by zimt28** [comment]
The problem with `onRun` is, that in some cases the actual page just flashes, before the login page appears.

**Comment by zimme** [comment]
@zimt28: How's this going?

**Comment by zimt28** [comment]
`onRun` works, but when I browse my app and log out, I won't get redirected to the login page sometimes. I just don't know what it is, maybe the hook doesn't run there, but it feels like it's something in my code which "blocks" the hook, as it seems to happen whan I browse certain pages. I then try in Chrome, not Safari, and there seems to be no problems.
I thought it might be running Trackers or something but I always stop them.
Any idea how to test why I don't get redirected?

**Comment by zimme** [comment]
I'll look into this problem this weekend, I have all day Sunday set aside for my packages.

**Comment by zimme** [comment]
So I've made some changes to the `noAuth` hook, would you mind trying version `3.1.0-rc.4` and see if the problem is resolved.

**Comment by zimme** [comment]
Also just having a `if (Meteor.userId())` check in the data function to only return data once logged in is probably a good idea.

Sometimes it's wanted to have data function to run before `onBeforeAction` because data is needed in the `onBeforeAction` check.

If you use `authenticate` hook in `onRun` then I believe it's prudent to use it in `onRerun` too.

**Comment by zimme** [comment]
Also, keep in mind that I made these hooks for `onBeforeActive`, it's only convenience logic to redirect user to a login page for certain routes automatically if you're not logged in, it's not "real" security, you should always lock down what the route is returning as it's data context based on if you're logged in.

What I really what is to add a new hook to iron:router which runs after `onRun` but before `data` and `onBeforeAction` to keep data and onBeforeActions from running unless you're authenticated and authorized.

**Comment by zimme** [comment]
and you should always check other onBeforeAction hooks to make sure the user is logged in also

**Comment by zimme** [comment]
Closing this as it's inactive, please @mention me if this is still a problem.
